export const environment = {
  production: true,
  authguardEnabled: true,
  ui: './assets/data/',
  baseUrl: 'https://quotebristolwest.bwproducers.com/PROD43/',
  baseWASUrl: 'https://rating.bristolwest.com/',
  loggerUrl: 'https://quotebristolwest.bwproducers.com/log/',
  //'http://localhost:3002/log/',
  enableLogger: true,
  // getQuoteNumberURL: 'https://nodedev.bwproducers.com/AFT43/bwprospectquotems/v1/quotes/quoteNumber/',
  quoteNumberAPI: 'bwautoquotems/v1/:mco/quoteNumber',
  rateBookAPI: 'bwautoquotems/v1/state/:ST/mco/:MC/ratebook',
  saveQuoteAPI: 'bwautoquotems/v1/quotes',
  retrieveQuoteAPI: 'bwautoquotems/v1/quotes/:quoteNumber',
  regUserURL: 'https://www.bristolwest.com/register?',
  rateQuoteAPI: 'bwautoquotems/v1/quotes',
  driversClueReportAPI: '/bwdriverms/v1/riskreports',
  vintelligenceSymbolsAPI: 'bwvehiclems/v1/vehicle/:vin',
  vintelligenceMakesAPI: 'bwvehiclems/v1/vehicle/years/:year/makes',
  vintelligenceModelsAPI: 'bwvehiclems/v1/vehicle/years/:year/makes/:make/models',
  vinPrefixAPI: 'bwvehiclems/v1/vehicle/vinprefixes?operation=searchForVinPrefixes',
  vintelSymbolsAPI: 'bwvehiclems/v1/vehicle/symbols?operation=getVehicleSymbols',
  addressVerificationAPI: 'PolicyHolderREST/scrubAddress',
  bwLookupPriCarAPI: 'bwlookupms/v1/lookup',
  bwTokenAPI: 'bwtokenms/v1/provider/providerId/userValidation',
  bwGenerateTokenAPI: 'bwtokenms/v1/provider/providerId/tokens',
  retrieveApplicantURL: 'bwprospectquotems/v1/quotes/QID/prospect?operation=retrieveProspects',
  saveApplicantURL: 'bwprospectquotems/v1/quotes/QID/prospect?operation=saveProspects',
  updateApplicantURL: 'bwprospectquotems/v1/quotes/QID/prospect?operation=updateProspects',
  retrieveDriversURL: 'bwdriverms/v1/quotes/QID?operation=retrieveDrivers',
  saveDriversURL: 'bwdriverms/v1/quotes/QID?operation=saveDrivers',
  vehicleHistoryReportURL: 'bwreportingms/v1/policies/QID/vehicleHistoryReport?operation=orderAndGetVehicleHistory',
  //helpTextURL: 'PolicyHolderREST/getAllHelpText?appid=BWR&mco=28&state=02&ratebook=All&lob=APV',
  propCreditReportURL: 'bwcreditcheckms/v1/reports/creditReport',
  propCreditStatusURL: 'bwcreditcheckms/v1/QID/creditReport/status',
  validValuesAPI:'PolicyHolderREST/getDropDownValues',
  validValues: 'PolicyHolderREST/getValidValues',
  BIPDvalidValues:'PolicyHolderREST/getOutOfStateLimitsValidValues',
  getStatesByZipcodeURL:'PolicyHolderREST/getstatebyzipcode?zipCode=garageZipCode',
  muleClientId : '60b43bbb5ad44156a1a1b135de412c8d',// '877178104829494b962d336636fe1f32', // old- 320fd4dc1bc14f8ea08b7e9f26fe5128
  muleClientSecret: 'F2e09bf167544a858Ffc5100ECEa3Ca6', //'F242333Bd8f44761b1eA15116CF5dBeE', // old - 7f2516bd472e43e2AD6DF875F3A86AE3
   consentValues: 'PolicyHolderREST/getConsentMessage',
  vinPrefillPOSTAPI: 'bwdriverms/v1/autoPrefillReport?filterBy=priorVehicles',
  vinPrefillGETStatusAPI:'bwdriverms/v1/autoPrefillReport/quoteNumber?filterBy=priorVehicles&masterCompany=:masterCompany',
  //# US153321-US292902-producerInformationSection
  getLicensedAgentsAPI: 'PolicyHolderREST/getLicensedAgents',
  edmrFormsAPI: '/bwdocumentms/v1/documents',
  emailVerificationAPI: 'PolicyHolderREST/validateEmail',
  emailDuplicateCheckAPI: 'PolicyHolderREST/checkForDupPolicyEmail',
  producerPOSTAPI: 'PolicyHolderREST/requestNewAgent',
  paymentRegion: 'PROD', //'SECURE2',
  paymentIframeURL: 'https://ipn2.paymentus.com/xotp/pm/frms?authToken=',
  splPaymentIframeURL: 'https://ipn2.paymentus.com/biller/federation/frms?v2=true&itok=',
  // 'https://secure2.paymentus.com/xotp/pm/frms?authToken=',
  paymentTokenURL: 'PolicyHolderREST/generateIframeToken',
  splPaymentTokenURL: 'PolicyHolderREST/generateSplIVRIframeToken',
  paymentIframeOrigin: 'https://ipn2.paymentus.com',
  // 'https://secure2.paymentus.com',
  paymentListMethods: 'pymtms/v1/customers/{AccountNumber}/paymentMethods?idType=ECN', //'https://apis-bweisg-aft.farmersinsurance.com/pymtms/v1/customers/{AccountNumber}/paymentMethods?idType=ECN',
  paymentDeleteMethod: 'pymtms/v1/customers/{AccountNumber}/paymentMethods/{PaymentMethodToken}', //'https://apis-bweisg-aft.farmersinsurance.com/pymtms/v1/customers/{AccountNumber}/paymentMethods/{PaymentMethodToken}',
  paymentEnrollAutoPay: 'pymtms/v1/accounts/{AccountNumber}/payment?idType=accountNumber&operation=recurringSetup',
  paymentCancelAutoPay: 'pymtms/v1/accounts/{AccountNumber}/payments/{referenceNumber}?accountIdType=billingAccountNumber&operation=cancelRecurring',
  paymentAutopayDetails: 'pymtms/v1/accounts/{AccountNumber}/payment?idType=billingAccountNumber&filter=recurringDetails',
  cancelSPLDownPayURL: 'pymtms/v1/accounts/{AccountNumber}/payments/{referenceNumber}?accountIdType=billingAccountNumber&operation=voidPayment',
  
  bindAPI: 'bwplcyms/v1/policies/{policyNumber}/quotes/{quoteNumber}?operation=bind',
  programGuideIA: 'https://www.bwproducers.com/BWPFiles/Guides/Foremost/{StateID}/Select_4.0_Rule_Guide.pdf',
  programGuideEA: 'https://www.bwproducers.com/BWPFiles/Guides/{StateID}/Select_4.0_Rule_Guide.pdf',
  invokeExstreamFeedURL :'PolicyHolderREST/invokeExstreamFeed',
  fetchDocumentsURL:'PolicyHolderREST/fetchDocument',

//DB libraries
storageLibrary: 'EDRAGONQ',
returnQuoteSearch : "https://www.bwproducers.com/",
  bwpFormsEA: 'https://www.bwproducers.com/Producers/ssologin.aspx?page=forms&agentCode={PID}&ssot={SID}',
  bwpFormsIA: 'https://www.iaproducers.com/Producers/ssologin.aspx?page=forms&agentCode={PID}&ssot={SID}'
};
